#!/usr/bin/with-contenv bash

source /assets/functions/00-container
check_container_initialized
check_service_initialized init 10-gcds
prepare_service both
PROCESS_NAME="gcds"
liftoff

date >/dev/null

if [ "$1" = "NOW" ]; then
    SYNC_BEGIN=+0
    MANUAL=TRUE
    LOG_LEVEL=DEBUG
fi

### Container Startup
print_debug "GCDS syncing routines Initialized on $(date)"

### Wait for Next time to start sync
  current_time=$(date +"%s")
  today=$(date +"%Y%m%d")

  if [[ $SYNC_BEGIN =~ ^\+(.*)$ ]]; then
        waittime=$(( ${BASH_REMATCH[1]} * 60 ))
  else
        print_debug "Getting other Target Time"
        target_time=$(date --date="${today} ${SYNC_BEGIN}" +"%s")
        if [[ "$target_time" < "$current_time" ]]; then
            target_time=$(($target_time + 24*60*60))
        fi
        waittime=$(($target_time - $current_time))
  fi

  sleep $waittime

### Commence Sync
  while true; do
    now=$(date +"%Y%m%d-%H%M%S")
    now_time=$(date +"%H:%M:%S")
    now_date=$(date +"%Y-%m-%d")
    perform_sync
    check_errors

    ### Go back to Sleep until next Backup time
    if var_true $MANUAL ; then
        exit 1;
    else
        sleep $(($SYNC_INTERVAL*60))
    fi
  done
fi
